server:
  port: 5001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/Courses?createDatabaseIfNotExist=true
    username: root
    password: techbankRootPsw

